#include <fstream>
#include <iostream>
#include <chrono>
#include <thread>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <math.h>
#include "opencv2/highgui.hpp"
#include <opencv2/opencv.hpp> 
#include <vector>
#include <sstream>
#include <ctype.h>
#include <cstdlib>
#include <unordered_map>
#include <string>
#include <filesystem>
#include <functional>
#include <utility>